sap.ui.define([], function () {
    "use strict";

    return {
        DETAIL_ACCESS_GUARD: "/detailAccessGuard",
        DETAIL_META: "/detailMeta",
        IS_LOADING: "/isLoading",
        PENDING_NAVIGATION_INTENT: "/pendingNavigationIntent",
        PERSISTENCE: "/persistence",
        PERSISTENCE_CURRENT_WRITE_REQUEST_ID: "/persistence/currentWriteRequestId",
        PERSISTENCE_HAS_VALID_LOCK: "/persistence/hasValidLock",
        PERSISTENCE_IS_AUTO_SAVE_IN_FLIGHT: "/persistence/isAutoSaveInFlight",
        PERSISTENCE_IS_MANUAL_SAVE_IN_FLIGHT: "/persistence/isManualSaveInFlight",
        PERSISTENCE_LAST_LOCK_REFRESH_AT: "/persistence/lastLockRefreshAt",
        PERSISTENCE_LAST_SAVE_ERROR: "/persistence/lastSaveError",
        PERSISTENCE_LAST_SAVED_AT: "/persistence/lastSavedAt",
        PERSISTENCE_LOCK_OWNER_SESSION_MATCHES: "/persistence/lockOwnerSessionMatches",
        PERSISTENCE_MESSAGE_KEY: "/persistence/messageKey",
        PERSISTENCE_NEXT_HEARTBEAT_AT: "/persistence/nextHeartbeatAt",
        PERSISTENCE_STATE: "/persistence/state",
        PERSISTENCE_TAXONOMY: "/persistence/taxonomy",
        READINESS_ANALYTICS: "/readiness/analytics",
        READINESS_APP: "/readiness/app",
        READINESS_APP_READY: "/readiness/app/ready",
        READINESS_DETAIL: "/readiness/detail",
        READINESS_SEARCH: "/readiness/search",
        SEARCH_BARRIERS_FAIL_SEGMENT: "/search/barriersFailSegment",
        SEARCH_CHECKS_FAIL_SEGMENT: "/search/checksFailSegment",
        SEARCH_MODE: "/searchMode",
        SEARCH_RETURN_CONTEXT: "/searchReturnContext",
        SAVE_IN_FLIGHT: "/saveInFlight",
        SESSION_ID: "/sessionId",
        TAB_SESSION_ID: "/tabSessionId",
        TAB_CONFLICT_STATE: "/tabConflictState",
        UI_BUSY_ANALYTICS: "/ui/busy/analytics",
        UI_BUSY_DETAIL: "/ui/busy/detail",
        UI_BUSY_EXPORT: "/ui/busy/export",
        // Legacy compatibility only: startup-related consumers must prefer /isLoading.
        UI_BUSY_GLOBAL: "/ui/busy/global",
        UI_BUSY_SEARCH_TABLE: "/ui/busy/searchTable",
        UI_FEEDBACK_CONFLICT_DIALOG: "/ui/feedback/conflictDialog",
        VALIDATION_SUMMARY: "/validationSummary",
        WORKFLOW_AUTOSAVE_ENABLED: "/autosaveEnabled",
        WORKFLOW_DETAIL_AUTOSAVE_LAST_SAVED_AT: "/workflow/detail/autosave/lastSavedAt",
        WORKFLOW_DETAIL_AUTOSAVE_STATE: "/workflow/detail/autosave/state",
        WORKFLOW_DETAIL_EDIT_MODE: "/workflow/detail/editMode",
        WORKFLOW_DETAIL_LOCK_STATE: "/workflow/detail/lock/state",
        WORKFLOW_DIRTY: "/isDirty",
        WORKFLOW_LOCK_LOST_REASON: "/lockLostReason",
        WORKFLOW_SEARCH_MODE: "/workflow/search/mode",
        WORKFLOW_SEARCH_SEGMENTS: "/workflow/search/segments",
        WORKFLOW_SEARCH_SEGMENTS_BARRIERS: "/workflow/search/segments/barriers",
        WORKFLOW_SEARCH_SEGMENTS_CHECKS: "/workflow/search/segments/checks"
    };
});
