sap.ui.define([], function () {
    "use strict";

    return Object.freeze({
        INFO_CARD_KEYS: Object.freeze({
            DATETIME: "datetime",
            EQUIPMENT: "equipment",
            LOCATION: "location",
            LPC: "lpc",
            OBSERVED: "observed",
            OBSERVER: "observer",
            PROFESSION: "profession"
        }),
        INFO_CARD_TEXT_KEYS: Object.freeze({
            DATETIME: "dateTimeBlockLabel",
            EQUIPMENT: "equipmentLabel",
            LOCATION: "locationLabel",
            LPC: "lpcLabel",
            OBSERVED: "observedLabel",
            OBSERVER: "observerLabel",
            PROFESSION: "professionLabel"
        }),
        INFO_CARD_TEXT_FALLBACKS: Object.freeze({
            DATETIME: "Date & Time",
            EQUIPMENT: "Equipment",
            LOCATION: "Location",
            LPC: "LPC",
            OBSERVED: "Observed",
            OBSERVER: "Observer",
            PROFESSION: "Profession"
        }),
        CARD_REQUIRED_KEYS: Object.freeze({
            datetime: Object.freeze(["basic.date", "basic.time", "basic.timezone"]),
            equipment: Object.freeze(["basic.equipment"]),
            observer: Object.freeze(["basic.OBSERVER_FULLNAME"]),
            observed: Object.freeze(["basic.OBSERVED_FULLNAME"]),
            location: Object.freeze(["basic.LOCATION_KEY"]),
            lpc: Object.freeze(["basic.LPC_KEY"]),
            profession: Object.freeze(["basic.PROF_KEY"])
        }),
        VIEW_DEFAULTS: Object.freeze({
            ATTACHMENT_CATEGORY_KEY: "GEN"
        }),
        ATTACHMENTS: Object.freeze({
            HINT_FALLBACK_EMPTY_TOKEN: "-",
            HINT_FALLBACK_SEPARATOR: " - ",
            HINT_TEXT_KEY: "attachmentUploadHint",
            MIME_REJECTED_TOAST_KEY: "attachmentMimeRejected",
            SIZE_REJECTED_TOAST_KEY: "attachmentSizeRejected",
            UPLOAD_BUSY_PATH: "/attachmentBusy",
            UPLOAD_DISABLED_TOAST_KEY: "attachmentUploadDisabled"
        }),
        STATES: Object.freeze({
            AUTOSAVING: "autosaving",
            CONFLICT: "conflict",
            DIRTY: "dirty",
            ERROR: "error",
            IDLE: "idle",
            IDLE_TIMEOUT_GRACE: "idleTimeoutGrace",
            LOCK_LOST: "lockLost",
            READ_ONLY: "readOnly",
            SAVED: "saved",
            SAVING: "saving"
        }),
        TAXONOMY: Object.freeze({
            PERMISSION_DENIED: "PERMISSION_DENIED",
            LOCK_EXPIRED: "LOCK_EXPIRED",
            LOCK_NOT_OWNED_BY_SESSION: "LOCK_NOT_OWNED_BY_SESSION",
            LOCK_STOLEN: "LOCK_STOLEN",
            LOCK_MISSING: "LOCK_MISSING",
            VERSION_CONFLICT: "VERSION_CONFLICT",
            VALIDATION_ERROR: "VALIDATION_ERROR",
            NETWORK_ERROR: "NETWORK_ERROR",
            TECHNICAL_ERROR: "TECHNICAL_ERROR"
        }),
        ACCESS_OPERATIONS: Object.freeze({
            CREATE: "01",
            CHANGE: "02",
            DISPLAY: "03",
            DELETE: "06"
        }),
        ACCESS_REASON_CODES: Object.freeze({
            AUTHORIZED: "AUTHORIZED",
            CREATE_DRAFT: "CREATE_DRAFT"
        }),
        CODES: Object.freeze({
            AUTOSAVE_EMPTY_DELTA: "AUTOSAVE_EMPTY_DELTA",
            AUTOSAVE_UNAVAILABLE: "AUTOSAVE_UNAVAILABLE",
            CREATE_HANDLER_MISSING: "CREATE_HANDLER_MISSING",
            DELETE_UNAVAILABLE: "DELETE_UNAVAILABLE",
            EXPIRED: "EXPIRED",
            INVALID_INPUT: "INVALID_INPUT",
            LOCK_ACQUIRE_FAILED: "LOCK_ACQUIRE_FAILED",
            LOCKED: "LOCKED",
            LOCKED_OWN_SESSION: "LOCKED_OWN_SESSION",
            KILLED: "KILLED",
            LOCK_REQUIRED: "LOCK_REQUIRED",
            MISSING_CLIENT_VERSION: "MISSING_CLIENT_VERSION",
            NO_CHANGES: "NO_CHANGES",
            NO_CHECKLIST: "NO_CHECKLIST",
            NO_CREATE_PERMISSION: "NO_CREATE_PERMISSION",
            NO_DELETE_PERMISSION: "NO_DELETE_PERMISSION",
            NO_EDIT_PERMISSION: "NO_EDIT_PERMISSION",
            NO_VIEW_PERMISSION: "NO_VIEW_PERMISSION",
            OK: "OK",
            PERMISSION_CHECK_FAILED: "PERMISSION_CHECK_FAILED",
            PERMISSION_CHECK_UNAVAILABLE: "PERMISSION_CHECK_UNAVAILABLE",
            SAVE_HANDLER_MISSING: "SAVE_HANDLER_MISSING",
            TECHNICAL_ERROR: "ERROR"
        }),
        MODEL_PATHS: Object.freeze({
            ATTACHMENTS: "/current/attachments",
            BASE: "/base",
            BASE_ATTACHMENTS: "/base/attachments",
            BASE_ROOT_ID: "/base/root/id",
            ROOT: "/current",
            ROOT_ID: "/current/root/id"
        }),
        REASONS: Object.freeze({
            AUTOSAVE_GUARD: "autosaveGuard",
            CREATE_DRAFT_PENDING: "createDraftPending",
            DETAIL_DELETE_COMPLETED: "detailDeleteCompleted",
            DETAIL_SAVE_COMPLETED: "detailSaveCompleted"
        }),
        ATTACHMENT_DELETED: "attachmentDeleted",
        ATTACHMENT_UPLOADED: "attachmentUploaded",
        CHECKLIST_DELETED: "checklistDeleted",
        DELETE_CHECKLIST_CONFIRM: "deleteChecklistConfirmText",
        DETAIL_CREATE_PERMISSION_DENIED: "detailCreatePermissionDenied",
        DETAIL_DELETE_PERMISSION_DENIED: "detailDeletePermissionDenied",
        DETAIL_DRAFT_CHANGED: "detailDraftChanged",
        DETAIL_DRAFT_CLEAN: "detailDraftClean",
        DETAIL_DRAFT_LOCAL: "detailDraftLocal",
        DETAIL_FORCED_READ_ONLY_TITLE: "detailForcedReadOnlyTitle",
        DETAIL_VIEW_PERMISSION_DENIED: "detailViewPermissionDenied",
        DETAIL_EMPTY_ATTACHMENTS_SAVED_TEXT: "detailEmptyAttachmentsSavedText",
        DETAIL_EMPTY_ATTACHMENTS_TEXT: "detailEmptyAttachmentsText",
        LOCK_ACQUIRE_FAILED: "lockAcquireFailed",
        LOCK_EXPIRED: "lockExpiredMessage",
        LOCK_EXPIRED_TAKEOVER_PROMPT: "lockExpiredTakeoverPrompt",
        LOCK_HEARTBEAT_FAILED: "lockHeartbeatFailed",
        LOCK_IDLE_TIMEOUT: "lockIdleTimeoutMessage",
        LOCK_KILLED: "lockKilledMessage",
        LOCK_LOST: "lockLostMessage",
        LOCK_LOST_BANNER_TITLE: "lockLostBannerTitle",
        LOCK_RELEASE_FAILED: "lockReleaseFailed",
        LOCK_STEAL_OWN_SESSION_PROMPT: "lockStealOwnSessionPrompt",
        LOCK_STATUS_FAILED: "lockStatusFailed",
        MODE_EDIT: "modeEdit",
        MODE_READ: "modeRead",
        NOTHING_TO_DELETE: "nothingToDelete",
        OBJECT_SAVED: "objectSaved",
        PERSISTENCE_AUTOSAVING: "persistenceAutosaving",
        PERSISTENCE_AUTOSAVE_PENDING_ATTACHMENTS: "persistenceAutosavePendingAttachments",
        PERSISTENCE_AUTOSAVE_SAVED: "persistenceAutosaveSaved",
        PERSISTENCE_CONFLICT: "persistenceConflict",
        PERSISTENCE_DIRTY: "persistenceDirty",
        PERSISTENCE_FORCED_READ_ONLY: "persistenceForcedReadOnly",
        PERSISTENCE_IDLE: "persistenceIdle",
        PERSISTENCE_IDLE_TIMEOUT_GRACE: "persistenceIdleTimeoutGrace",
        PERSISTENCE_LOCK_EXPIRED: "persistenceLockExpired",
        PERSISTENCE_LOCK_LOST: "persistenceLockLost",
        PERSISTENCE_LOCK_MISSING: "persistenceLockMissing",
        PERSISTENCE_LOCK_NOT_OWNED: "persistenceLockNotOwned",
        PERSISTENCE_LOCK_STOLEN: "persistenceLockStolen",
        PERSISTENCE_NETWORK_ERROR: "persistenceNetworkError",
        PERSISTENCE_NO_CHANGES: "persistenceNoChanges",
        PERSISTENCE_PERMISSION_DENIED: "persistencePermissionDenied",
        PERSISTENCE_SAVED: "persistenceSaved",
        PERSISTENCE_SAVED_AT: "persistenceSavedAt",
        PERSISTENCE_SAVING: "persistenceSaving",
        PERSISTENCE_TECHNICAL_ERROR: "persistenceTechnicalError",
        PERSISTENCE_TOOLTIP_WITH_DETAILS: "persistenceTooltipWithDetails",
        PERSISTENCE_VALIDATION_ERROR: "persistenceValidationError",
        REQUIRED_FIELD_HINT: "requiredFieldHint",
        STATUS_CLOSED: "statusClosed",
        STATUS_DRAFT: "statusDraft",
        STATUS_FAILED: "statusFailed",
        STATUS_OK: "statusOk",
        STATUS_REGISTERED: "statusRegistered",
        VALIDATION_SUMMARY_LINK_MANY: "validationSummaryLinkMany",
        VALIDATION_SUMMARY_LINK_SINGLE: "validationSummaryLinkSingle",
        VALIDATION_SUMMARY_TITLE: "validationSummaryTitle",
        VALIDATION_SUMMARY_TITLE_COUNT: "validationSummaryTitleCount",
        HEARTBEAT_LOCKED_ACTIVE: "heartbeatLockedActive",
        HEARTBEAT_DRAFT_CREATE: "heartbeatDraftCreate",
        HEARTBEAT_INACTIVE: "heartbeatInactive",
        AUTOSAVE_WAITING: "autosaveWaiting",
        AUTOSAVE_SAVING: "autosaveSaving",
        AUTOSAVE_SAVED: "autosaveSaved",
        AUTOSAVE_ERROR: "autosaveError",
        AUTOSAVE_DISABLED: "autosaveDisabled",
        AUTOSAVE_CREATE_DRAFT: "autosaveCreateDraft",
        IDLE_TIMEOUT_GRACE_BANNER_TITLE: "idleTimeoutGraceBannerTitle",
        ATTACHMENT_DRAFT_STAGE_HINT: "attachmentDraftStageHint"
    });
});
