sap.ui.define([], function () {
    "use strict";

    return Object.freeze({
        DETAIL: Object.freeze({
            AUTHORIZED: "AUTHORIZED",
            AUTOSAVE_EMPTY_DELTA: "AUTOSAVE_EMPTY_DELTA",
            AUTOSAVE_UNAVAILABLE: "AUTOSAVE_UNAVAILABLE",
            CREATE_DRAFT: "CREATE_DRAFT",
            EXPIRED: "EXPIRED",
            INTEGRATION_CONFIRM_REQUIRED: "INTEGRATION_CONFIRM_REQUIRED",
            INVALID_INPUT: "INVALID_INPUT",
            VALIDATION_ERROR: "VALIDATION_ERROR",
            VERSION_CONFLICT: "VERSION_CONFLICT",
            TECHNICAL_ERROR: "TECHNICAL_ERROR",
            LOCK_MISSING: "LOCK_MISSING",
            LOCK_EXPIRED: "LOCK_EXPIRED",
            LOCK_STOLEN: "LOCK_STOLEN",
            LOCK_NOT_OWNED_BY_SESSION: "LOCK_NOT_OWNED_BY_SESSION",
            PERMISSION_DENIED: "PERMISSION_DENIED",
            LOCK_OK: "LOCK_OK",
            LOCK_REQUIRED: "LOCK_REQUIRED",
            LOCKED: "LOCKED",
            LOCKED_OWN_SESSION: "LOCKED_OWN_SESSION",
            KILLED: "KILLED",
            SAVE_HANDLER_MISSING: "SAVE_HANDLER_MISSING",
            CREATE_HANDLER_MISSING: "CREATE_HANDLER_MISSING",
            DELETE_UNAVAILABLE: "DELETE_UNAVAILABLE",
            MISSING_CLIENT_VERSION: "MISSING_CLIENT_VERSION",
            NO_CHECKLIST: "NO_CHECKLIST",
            PERMISSION_CHECK_UNAVAILABLE: "PERMISSION_CHECK_UNAVAILABLE",
            PERMISSION_CHECK_FAILED: "PERMISSION_CHECK_FAILED",
            NO_CREATE_PERMISSION: "NO_CREATE_PERMISSION",
            NO_EDIT_PERMISSION: "NO_EDIT_PERMISSION",
            NO_DELETE_PERMISSION: "NO_DELETE_PERMISSION",
            NO_VIEW_PERMISSION: "NO_VIEW_PERMISSION"
        }),
        FLOW: Object.freeze({
            EXPIRED: "EXPIRED",
            KILLED: "KILLED",
            CREATE_DRAFT: "CREATE_DRAFT",
            LOCKED: "LOCKED",
            LOCKED_OWN_SESSION: "LOCKED_OWN_SESSION",
            OK: "OK",
            SAVED: "SAVED",
            NO_CHANGES: "NO_CHANGES"
        })
    });
});
