sap.ui.define([
    "PRODUCTION_CONTROL_CHECKLIST/model/StatePaths"
], function (StatePaths) {
    "use strict";

    return Object.freeze({
        UI_BUSY_GLOBAL: StatePaths.UI_BUSY_GLOBAL,
        UI_BUSY_SEARCH_TABLE: StatePaths.UI_BUSY_SEARCH_TABLE,
        UI_BUSY_DETAIL: StatePaths.UI_BUSY_DETAIL,
        WORKFLOW_DETAIL_EDIT_MODE: StatePaths.WORKFLOW_DETAIL_EDIT_MODE,
        WORKFLOW_DETAIL_LOCK_STATE: StatePaths.WORKFLOW_DETAIL_LOCK_STATE,
        WORKFLOW_DETAIL_AUTOSAVE_STATE: StatePaths.WORKFLOW_DETAIL_AUTOSAVE_STATE,
        WORKFLOW_DETAIL_AUTOSAVE_LAST_SAVED_AT: StatePaths.WORKFLOW_DETAIL_AUTOSAVE_LAST_SAVED_AT,
        WORKFLOW_SEARCH_MODE: StatePaths.WORKFLOW_SEARCH_MODE,
        WORKFLOW_SEARCH_SEGMENTS: StatePaths.WORKFLOW_SEARCH_SEGMENTS
    });
});
