from utils.odata import ODATA_NS


def build_metadata() -> str:
    return f'''<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx">
 <edmx:DataServices m:DataServiceVersion="2.0" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
  <Schema Namespace="{ODATA_NS}" xmlns="http://schemas.microsoft.com/ado/2008/09/edm" xmlns:sap="http://www.sap.com/Protocols/SAPData">
   <EntityType Name="FunctionResult"><Key><PropertyRef Name="RequestId"/></Key><Property Name="RequestId" Type="Edm.String" Nullable="false" sap:label="RequestId"/><Property Name="Ok" Type="Edm.Boolean" sap:label="Ok"/><Property Name="Success" Type="Edm.Boolean" sap:label="Success"/><Property Name="Message" Type="Edm.String" sap:label="Message"/><Property Name="AggChangedOn" Type="Edm.DateTime" sap:label="AggChangedOn"/><Property Name="ReasonCode" Type="Edm.String" sap:label="ReasonCode"/><Property Name="ExpiresOn" Type="Edm.DateTime" sap:label="ExpiresOn"/><Property Name="LockExpires" Type="Edm.DateTime" sap:label="LockExpires"/><Property Name="IsKilled" Type="Edm.Boolean" sap:label="IsKilled"/><Property Name="Status" Type="Edm.String" sap:label="Status"/><Property Name="RootKey" Type="Edm.String" sap:label="RootKey"/><Property Name="Action" Type="Edm.String" sap:label="Action"/><Property Name="Owner" Type="Edm.String" sap:label="Owner"/><Property Name="OwnerSession" Type="Edm.String" sap:label="OwnerSession"/></EntityType>
   <EntityType Name="SaveChangesResponse"><Key><PropertyRef Name="pcct_uuid"/></Key><Property Name="pcct_uuid" Type="Edm.String" Nullable="false"/><Property Name="changed_on" Type="Edm.DateTime"/><Property Name="version_number" Type="Edm.Int32"/></EntityType>
   <EntityType Name="HierarchyNode"><Key><PropertyRef Name="NodeID"/></Key><Property Name="NodeID" Type="Edm.String" Nullable="false"/><Property Name="HierarchyLevel" Type="Edm.Int32"/><Property Name="Description" Type="Edm.String"/><Property Name="ParentNodeID" Type="Edm.String"/><Property Name="DrillState" Type="Edm.String"/></EntityType>
   <EntityType Name="ExportRow"><Key><PropertyRef Name="RootKey"/><PropertyRef Name="ItemType"/><PropertyRef Name="Num"/></Key><Property Name="RootKey" Type="Edm.String" Nullable="false"/><Property Name="Id" Type="Edm.String"/><Property Name="Lpc" Type="Edm.String"/><Property Name="LpcText" Type="Edm.String"/><Property Name="Profession" Type="Edm.String"/><Property Name="ProfessionText" Type="Edm.String"/><Property Name="LocationKey" Type="Edm.String"/><Property Name="Status" Type="Edm.String"/><Property Name="EquipName" Type="Edm.String"/><Property Name="ChangedOn" Type="Edm.DateTime"/><Property Name="DateCheck" Type="Edm.DateTime"/><Property Name="ItemType" Type="Edm.String" Nullable="false"/><Property Name="Num" Type="Edm.Int32" Nullable="false"/><Property Name="Text" Type="Edm.String"/><Property Name="Comment" Type="Edm.String"/><Property Name="Result" Type="Edm.Boolean"/></EntityType>
   <EntityType Name="ChecklistSearch"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false" sap:label="Key"/><Property Name="Id" Type="Edm.String"/><Property Name="DateCheck" Type="Edm.DateTime"/><Property Name="TimeCheck" Type="Edm.String"/><Property Name="TimeZone" Type="Edm.String"/><Property Name="LocationKey" Type="Edm.String"/><Property Name="Bukrs" Type="Edm.String"/><Property Name="Lpc" Type="Edm.String"/><Property Name="LpcText" Type="Edm.String"/><Property Name="Profession" Type="Edm.String"/><Property Name="ProfessionText" Type="Edm.String"/><Property Name="EquipName" Type="Edm.String"/><Property Name="Status" Type="Edm.String"/><Property Name="SourceKey" Type="Edm.String"/><Property Name="IntegrationFlag" Type="Edm.Boolean"/><Property Name="CreatedOn" Type="Edm.DateTime"/><Property Name="ChangedOn" Type="Edm.DateTime"/><Property Name="HasFailedChecks" Type="Edm.Boolean"/><Property Name="HasFailedBarriers" Type="Edm.Boolean"/><Property Name="SuccessChecksRate" Type="Edm.Double"/><Property Name="SuccessBarriersRate" Type="Edm.Double"/><Property Name="ChecksTotal" Type="Edm.Int32"/><Property Name="BarriersTotal" Type="Edm.Int32"/></EntityType>
   <EntityType Name="ChecklistRoot"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="RequestId" Type="Edm.String"/><Property Name="Id" Type="Edm.String"/><Property Name="ChangedOn" Type="Edm.DateTime"/><Property Name="CreatedOn" Type="Edm.DateTime"/><Property Name="VersionNumber" Type="Edm.Int32"/><Property Name="Status" Type="Edm.String"/><Property Name="HasFailedChecks" Type="Edm.Boolean"/><Property Name="HasFailedBarriers" Type="Edm.Boolean"/><Property Name="SuccessChecksRate" Type="Edm.Double"/><Property Name="SuccessBarriersRate" Type="Edm.Double"/><Property Name="ChecksTotal" Type="Edm.Int32"/><Property Name="BarriersTotal" Type="Edm.Int32"/></EntityType>
   <EntityType Name="ChecklistBasicInfo"><Key><PropertyRef Name="RootKey"/></Key><Property Name="RootKey" Type="Edm.String" Nullable="false"/><Property Name="LocationKey" Type="Edm.String"/><Property Name="LocationName" Type="Edm.String"/><Property Name="LocationText" Type="Edm.String"/><Property Name="Bukrs" Type="Edm.String"/><Property Name="ObserverPernr" Type="Edm.String"/><Property Name="ObserverFullname" Type="Edm.String"/><Property Name="ObserverPosition" Type="Edm.String"/><Property Name="ObserverOrgUnit" Type="Edm.String"/><Property Name="ObservedPernr" Type="Edm.String"/><Property Name="ObservedFullname" Type="Edm.String"/><Property Name="ObservedPosition" Type="Edm.String"/><Property Name="ObservedOrgUnit" Type="Edm.String"/><Property Name="Lpc" Type="Edm.String"/><Property Name="Profession" Type="Edm.String"/><Property Name="DateCheck" Type="Edm.DateTime"/><Property Name="TimeCheck" Type="Edm.String"/><Property Name="TimeZone" Type="Edm.String"/><Property Name="EquipName" Type="Edm.String"/></EntityType>
   <EntityType Name="ChecklistCheck"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="RootKey" Type="Edm.String"/><Property Name="ChecksNum" Type="Edm.Int32"/><Property Name="Text" Type="Edm.String"/><Property Name="Comment" Type="Edm.String"/><Property Name="Result" Type="Edm.Boolean"/><Property Name="ChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="ChecklistBarrier"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="RootKey" Type="Edm.String"/><Property Name="BarriersNum" Type="Edm.Int32"/><Property Name="Text" Type="Edm.String"/><Property Name="Comment" Type="Edm.String"/><Property Name="Result" Type="Edm.Boolean"/><Property Name="ChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="DictionaryItem"><Key><PropertyRef Name="Domain"/><PropertyRef Name="Key"/></Key><Property Name="Domain" Type="Edm.String" Nullable="false"/><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="Text" Type="Edm.String"/></EntityType>
   <EntityType Name="PersonVH"><Key><PropertyRef Name="Pernr"/></Key><Property Name="Pernr" Type="Edm.String" Nullable="false"/><Property Name="FirstName" Type="Edm.String"/><Property Name="LastName" Type="Edm.String"/><Property Name="MiddleName" Type="Edm.String"/><Property Name="Position" Type="Edm.String"/><Property Name="OrgUnit" Type="Edm.String"/><Property Name="IntegrationName" Type="Edm.String"/><Property Name="Begda" Type="Edm.DateTime"/><Property Name="Endda" Type="Edm.DateTime"/><Property Name="ChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="LastChange"><Key><PropertyRef Name="RootKey"/></Key><Property Name="RootKey" Type="Edm.String" Nullable="false"/><Property Name="AggChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="LockStatus"><Key><PropertyRef Name="RootKey"/></Key><Property Name="RootKey" Type="Edm.String" Nullable="false"/><Property Name="Ok" Type="Edm.Boolean"/><Property Name="Success" Type="Edm.Boolean"/><Property Name="ReasonCode" Type="Edm.String"/><Property Name="Owner" Type="Edm.String"/><Property Name="ExpiresOn" Type="Edm.DateTime"/><Property Name="LockExpires" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="ChecklistPermission"><Key><PropertyRef Name="RootKey"/></Key><Property Name="RootKey" Type="Edm.String" Nullable="false"/><Property Name="UserId" Type="Edm.String"/><Property Name="AuthObject" Type="Edm.String"/><Property Name="CreateOperation" Type="Edm.String"/><Property Name="ViewOperation" Type="Edm.String"/><Property Name="ChangeOperation" Type="Edm.String"/><Property Name="DeleteOperation" Type="Edm.String"/><Property Name="GrantedOperations" Type="Edm.String"/><Property Name="CanCreate" Type="Edm.Boolean"/><Property Name="CanView" Type="Edm.Boolean"/><Property Name="CanEdit" Type="Edm.Boolean"/><Property Name="CanDelete" Type="Edm.Boolean"/><Property Name="ReasonCode" Type="Edm.String"/><Property Name="Message" Type="Edm.String"/></EntityType>
   <EntityType Name="CurrentUser"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="FullName" Type="Edm.String"/><Property Name="PermissionsCsv" Type="Edm.String"/><Property Name="PermissionRulesJson" Type="Edm.String"/><Property Name="CanView" Type="Edm.Boolean"/><Property Name="CanEdit" Type="Edm.Boolean"/><Property Name="CanDelete" Type="Edm.Boolean"/><Property Name="SummaryText" Type="Edm.String"/></EntityType>
   <EntityType Name="RuntimeSettings"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="CacheToleranceMs" Type="Edm.Int32"/><Property Name="HeartbeatIntervalSec" Type="Edm.Int32"/><Property Name="StatusPollIntervalSec" Type="Edm.Int32"/><Property Name="LockTtlSec" Type="Edm.Int32"/><Property Name="IdleTimeoutSec" Type="Edm.Int32"/><Property Name="AutoSaveDebounceMs" Type="Edm.Int32"/><Property Name="RequiredFieldsJson" Type="Edm.String"/><Property Name="FrontendVariablesJson" Type="Edm.String"/><Property Name="UploadPolicyJson" Type="Edm.String"/></EntityType>
   <EntityType Name="SimpleAnalytical"><Key><PropertyRef Name="Key"/></Key><Property Name="Key" Type="Edm.String" Nullable="false"/><Property Name="SelectedYear" Type="Edm.Int32"/><Property Name="PreviousYear" Type="Edm.Int32"/><Property Name="AvailableYearsJson" Type="Edm.String"/><Property Name="Total" Type="Edm.Int32"/><Property Name="Monthly" Type="Edm.Int32"/><Property Name="FailedChecks" Type="Edm.Int32"/><Property Name="FailedBarriers" Type="Edm.Int32"/><Property Name="FailedChecklistCount" Type="Edm.Int32"/><Property Name="FailedBarrierChecklistCount" Type="Edm.Int32"/><Property Name="ClosedCount" Type="Edm.Int32"/><Property Name="RegisteredCount" Type="Edm.Int32"/><Property Name="AvgChecksRate" Type="Edm.Double"/><Property Name="AvgBarriersRate" Type="Edm.Double"/><Property Name="Healthy" Type="Edm.Int32"/><Property Name="RefreshedAt" Type="Edm.String"/><Property Name="Source" Type="Edm.String"/><Property Name="SourceText" Type="Edm.String"/></EntityType>
   <EntityType Name="WorkflowAnalyticsBreakdown"><Key><PropertyRef Name="Dimension"/><PropertyRef Name="Metric"/><PropertyRef Name="BucketKey"/></Key><Property Name="Dimension" Type="Edm.String" Nullable="false"/><Property Name="Metric" Type="Edm.String" Nullable="false"/><Property Name="BucketKey" Type="Edm.String" Nullable="false"/><Property Name="Label" Type="Edm.String"/><Property Name="Value" Type="Edm.Int32"/><Property Name="Order" Type="Edm.Int32"/></EntityType>
   <EntityType Name="AnalyticsRefreshState"><Key><PropertyRef Name="TaskKey"/></Key><Property Name="TaskKey" Type="Edm.String" Nullable="false"/><Property Name="TaskName" Type="Edm.String"/><Property Name="Status" Type="Edm.String"/><Property Name="IsRunning" Type="Edm.Boolean"/><Property Name="RequestedAt" Type="Edm.String"/><Property Name="RequestedBy" Type="Edm.String"/><Property Name="StartedAt" Type="Edm.String"/><Property Name="FinishedAt" Type="Edm.String"/><Property Name="LastSuccessAt" Type="Edm.String"/><Property Name="LastError" Type="Edm.String"/><Property Name="LastMessage" Type="Edm.String"/><Property Name="ActiveRunId" Type="Edm.String"/></EntityType>
   <EntityType Name="AttachmentFolder"><Key><PropertyRef Name="FolderKey"/></Key><Property Name="FolderKey" Type="Edm.String" Nullable="false"/><Property Name="RootKey" Type="Edm.String"/><Property Name="Title" Type="Edm.String"/><Property Name="CreatedOn" Type="Edm.DateTime"/><Property Name="ChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityType Name="Attachment"><Key><PropertyRef Name="AttachmentKey"/></Key><Property Name="AttachmentKey" Type="Edm.String" Nullable="false"/><Property Name="Key" Type="Edm.String"/><Property Name="RootKey" Type="Edm.String"/><Property Name="ParentKey" Type="Edm.String"/><Property Name="FolderKey" Type="Edm.String"/><Property Name="CategoryKey" Type="Edm.String"/><Property Name="CategoryText" Type="Edm.String"/><Property Name="Type" Type="Edm.String"/><Property Name="FileName" Type="Edm.String"/><Property Name="Name" Type="Edm.String"/><Property Name="MimeType" Type="Edm.String"/><Property Name="Description" Type="Edm.String"/><Property Name="FileSize" Type="Edm.Int32"/><Property Name="FileSizeContent" Type="Edm.Int32"/><Property Name="Value" Type="Edm.Binary"/><Property Name="ScanStatus" Type="Edm.String"/><Property Name="ScannedOn" Type="Edm.DateTime"/><Property Name="CreatedOn" Type="Edm.DateTime"/><Property Name="ChangedOn" Type="Edm.DateTime"/></EntityType>
   <EntityContainer Name="{ODATA_NS}_Entities" m:IsDefaultEntityContainer="true">
    <EntitySet Name="ChecklistSearchSet" EntityType="{ODATA_NS}.ChecklistSearch" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="true" sap:requires-filter="false" sap:addressable="false"/>
    <EntitySet Name="ChecklistRootSet" EntityType="{ODATA_NS}.ChecklistRoot" sap:creatable="false" sap:updatable="false" sap:deletable="true" sap:searchable="false" sap:requires-filter="false" sap:addressable="true"/>
    <EntitySet Name="ChecklistBasicInfoSet" EntityType="{ODATA_NS}.ChecklistBasicInfo" sap:creatable="false" sap:updatable="true" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="ChecklistCheckSet" EntityType="{ODATA_NS}.ChecklistCheck" sap:creatable="false" sap:updatable="true" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="ChecklistBarrierSet" EntityType="{ODATA_NS}.ChecklistBarrier" sap:creatable="false" sap:updatable="true" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="DictionaryItemSet" EntityType="{ODATA_NS}.DictionaryItem" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="PersonVHSet" EntityType="{ODATA_NS}.PersonVH" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="true" sap:requires-filter="false" sap:addressable="true"/>
    <EntitySet Name="LastChangeSet" EntityType="{ODATA_NS}.LastChange" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="LockStatusSet" EntityType="{ODATA_NS}.LockStatus" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="ChecklistPermissionSet" EntityType="{ODATA_NS}.ChecklistPermission" sap:creatable="false" sap:updatable="false" sap:deletable="false"/>
    <EntitySet Name="ChecklistCreatePermissionSet" EntityType="{ODATA_NS}.ChecklistPermission" sap:creatable="false" sap:updatable="false" sap:deletable="false"/>
    <EntitySet Name="CurrentUserSet" EntityType="{ODATA_NS}.CurrentUser" sap:creatable="false" sap:updatable="false" sap:deletable="false"/>
    <EntitySet Name="RuntimeSettingsSet" EntityType="{ODATA_NS}.RuntimeSettings" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="false" sap:addressable="true"/>
    <EntitySet Name="SimpleAnalyticalSet" EntityType="{ODATA_NS}.SimpleAnalytical" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="false" sap:addressable="true"/>
    <EntitySet Name="WorkflowAnalyticsBreakdownSet" EntityType="{ODATA_NS}.WorkflowAnalyticsBreakdown" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="AnalyticsRefreshStateSet" EntityType="{ODATA_NS}.AnalyticsRefreshState" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="false" sap:addressable="true"/>
    <EntitySet Name="AttachmentFolderSet" EntityType="{ODATA_NS}.AttachmentFolder" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <EntitySet Name="AttachmentSet" EntityType="{ODATA_NS}.Attachment" sap:creatable="true" sap:updatable="true" sap:deletable="true" sap:searchable="false" sap:requires-filter="true" sap:addressable="true"/>
    <FunctionImport Name="LockAcquire" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="LockHeartbeat" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="LockRelease" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="CreateChecklist" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="CopyChecklist" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="AutoSave" ReturnType="{ODATA_NS}.SaveChangesResponse" m:HttpMethod="POST"/>
    <FunctionImport Name="SaveChanges" ReturnType="{ODATA_NS}.SaveChangesResponse" m:HttpMethod="POST"/>
    <FunctionImport Name="SetChecklistStatus" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="AnalyticsRefreshTrigger" ReturnType="{ODATA_NS}.FunctionResult" m:HttpMethod="POST"/>
    <FunctionImport Name="GetHierarchy" ReturnType="Collection({ODATA_NS}.HierarchyNode)" m:HttpMethod="GET"/>
    <FunctionImport Name="ReportExport" ReturnType="Collection({ODATA_NS}.ExportRow)" m:HttpMethod="POST"/>
   </EntityContainer>
  </Schema>
 </edmx:DataServices>
</edmx:Edmx>'''
