sap.ui.define([
    "sap/ui/core/UIComponent",
    "sap/ui/model/json/JSONModel",
    "sap/ui/Device",
    "PRODUCTION_CONTROL_CHECKLIST/model/ModelFactory",
    "PRODUCTION_CONTROL_CHECKLIST/model/StatePaths",
    "PRODUCTION_CONTROL_CHECKLIST/service/SmartSearchAdapter",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/ManagerFacade",
    "PRODUCTION_CONTROL_CHECKLIST/service/shared/DeltaPayloadBuilder",
    "PRODUCTION_CONTROL_CHECKLIST/service/shared/CreateSentinel",
    "PRODUCTION_CONTROL_CHECKLIST/service/backend/GatewayBackendService",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/DebugLogger",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/RuntimeTimerSanitizer",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/TimeConfigService",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/CtxFactory",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/execution/EffectApplier",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/execution/FeedbackPolicy",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/WorkflowCoordinator",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentLockReleaseRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentSaveGuardRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentInitRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentModelInitRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentMainServiceRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentCoreInitRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/runtime/component/ComponentStateSeedRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/TelemetryRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/LayoutStateRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/ActionDispatcher",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/ActionContract",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/WorkflowTelemetry",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/InteractionFX",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/ThemeService",
    "PRODUCTION_CONTROL_CHECKLIST/service/framework/ComponentAppRuntime",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/detail/DetailFacade",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/shared/usecases/ApplyRuntimeSettingsUseCase",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/shared/usecases/EnsureDictLoadedUseCase",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/shared/usecases/InitializeAppUseCase",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/shared/usecases/LoadCurrentUserUseCase",
    "PRODUCTION_CONTROL_CHECKLIST/service/domain/shared/usecases/DiagnosticsUseCase"
], function (
    UIComponent,
    JSONModel,
    Device,
    ModelFactory,
    StatePaths,
    SmartSearchAdapter,
    ManagerFacade,
    DeltaPayloadBuilder,
    CreateSentinel,
    GatewayBackendService,
    DebugLogger,
    RuntimeTimerSanitizer,
    TimeConfigService,
    CtxFactory,
    EffectApplier,
    FeedbackPolicy,
    WorkflowCoordinator,
    ComponentLockReleaseRuntime,
    ComponentSaveGuardRuntime,
    ComponentInitRuntime,
    ComponentModelInitRuntime,
    ComponentMainServiceRuntime,
    ComponentCoreInitRuntime,
    ComponentStateSeedRuntime,
    TelemetryRuntime,
    LayoutStateRuntime,
    ActionDispatcher,
    ActionContract,
    WorkflowTelemetry,
    InteractionFX,
    ThemeService,
    ComponentAppRuntime,
    DetailFacade,
    ApplyRuntimeSettingsUseCase,
    EnsureDictLoadedUseCase,
    InitializeAppUseCase,
    LoadCurrentUserUseCase,
    DiagnosticsUseCase
) {
    "use strict";

    function init(oComponent, aInitArgs) {
        oComponent._oInteractionFX = InteractionFX;
        return ComponentInitRuntime.runInit.call(oComponent, aInitArgs || [], {
            UIComponent: UIComponent,
            ModelFactory: ModelFactory,
            SmartSearchAdapter: SmartSearchAdapter,
            Managers: ManagerFacade,
            JSONModel: JSONModel,
            WorkflowCoordinator: WorkflowCoordinator,
            DeltaPayloadBuilder: DeltaPayloadBuilder,
            GatewayBackendService: GatewayBackendService,
            DebugLogger: DebugLogger,
            RuntimeTimerSanitizer: RuntimeTimerSanitizer,
            TimeConfigService: TimeConfigService,
            ApplyRuntimeSettingsUseCase: ApplyRuntimeSettingsUseCase,
            EnsureDictLoadedUseCase: EnsureDictLoadedUseCase,
            InitializeAppUseCase: InitializeAppUseCase,
            LoadCurrentUserUseCase: LoadCurrentUserUseCase,
            DiagnosticsUseCase: DiagnosticsUseCase,
            CtxFactory: CtxFactory,
            EffectApplier: EffectApplier,
            FeedbackPolicy: FeedbackPolicy,
            ComponentRuntimeSupport: ComponentAppRuntime.buildComponentRuntimeSupport(),
            ComponentLockReleaseRuntime: ComponentLockReleaseRuntime,
            ComponentSaveGuardRuntime: ComponentSaveGuardRuntime,
            ComponentModelInitRuntime: ComponentModelInitRuntime,
            ComponentMainServiceRuntime: ComponentMainServiceRuntime,
            ComponentCoreInitRuntime: ComponentCoreInitRuntime,
            ComponentStateSeedRuntime: ComponentStateSeedRuntime,
            TelemetryRuntime: TelemetryRuntime,
            LayoutStateRuntime: LayoutStateRuntime,
            StatePaths: StatePaths,
            DetailFacade: DetailFacade,
            ActionDispatcher: ActionDispatcher,
            ActionContract: ActionContract,
            WorkflowTelemetry: WorkflowTelemetry,
            CreateSentinel: CreateSentinel,
            Device: Device,
            ThemeRuntime: ThemeService
        });
    }

    return {
        init: init
    };
});
